config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  get 'control_users/index'
  get 'shares/index'
  get 'reports/index'
  get 'welcome/index'
  resources :clients, shallow: true do
    resources :lawsuits
  end
  resources :lawsuits, shallow: true do
    resources :payments
  end
  resources :lawsuits, shallow: true do
    resources :observations
  end
  resources :lawsuits, shallow: true do
    resources :annexes
  end
  resources :lawsuits, shallow: true do
    resources :shares
  end
  resources :addresses

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client
  validates :street, :district, :zipcode, :city, :state, :addresstype, presence: true
end

app/models/annex.rb
class Annex < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
  mount_uploader :document, AnnexUploader
end

app/models/client.rb
class Client < ApplicationRecord
  has_one :address
  belongs_to :user
  has_many :lawsuits
  validates :cpf, :rg, uniqueness: true, presence: true, numericality: { only_integer: true }
  validates :name, :born, :sex, :email, :telephone, :celphone, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
  on: :create }

  accepts_nested_attributes_for :address
end

app/models/kind.rb
class Kind < ApplicationRecord
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/lawsuit.rb
class Lawsuit < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :venue
  belongs_to :kind
  belongs_to :status
  has_many :annexes
  has_many :observations
  has_many :payments
  has_many :shares
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :profiles
	validates :name, uniqueness: true, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :lawsuit
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :lawsuit
end

app/models/status.rb
class Status < ApplicationRecord 
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/user.rb
class User < ApplicationRecord
	enum role: [:normal_user, :admin]
  has_many :clients
  has_many :annexes
  has_one :profile
  has_many :lawsuits
  has_many :observations
  has_many :accounts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
	has_many :lawsuits
	validates :name, presence: true
end

app/controllers/lawsuits_controller.rb
class LawsuitsController < ApplicationController
  before_action :authenticate_user!, :profile_test
  before_action :set_lawsuit, only: [:show, :edit, :update, :destroy]
  before_action :load_client, only: [:new, :create]
  before_action :load_observation, :load_payment, :load_annex, :load_share, only: [:show, :destroy]

  def index
    @q = Lawsuit.ransack(params[:q])
    if params[:q]
      @lawsuits = @q.result
      @lawsuits = policy_scope(@lawsuits).paginate(page: params[:page], per_page: 1)
      if @lawsuits == []
        respond_to do |format|
            format.html { redirect_to lawsuits_url, notice: 'Não foi encontrado.' }
        end
      end
    else
    @lawsuits = policy_scope(Lawsuit).order("status_id ASC").paginate(page: params[:page], per_page: 8)
    end
  end

  def show
    @define_author_a = Share.where(lawsuit_id: @lawsuit.id)
    @define_author_b = @define_author_a.where(email: current_user.email)
    if @define_author_b != []
      true
    else
      authorize @lawsuit
    end
  end

  def new
    @lawsuit = Lawsuit.new
  end

  def edit
  end

  def create
    @lawsuit = @client.lawsuits.new(lawsuit_params)
    @lawsuit.user_id = current_user.id
    @lawsuit.amount_paid = 0
    @lawsuit.amount_rest = @lawsuit.amount
    respond_to do |format|
      if @lawsuit.save
        format.html { redirect_to @lawsuit, notice: 'Processo Cadastrado com Sucesso.' }
        format.json { render :show, status: :created, location: @lawsuit }
      else
        format.html { render :new }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lawsuit
    @lawsuit.amount_rest = @lawsuit.amount - @lawsuit.amount_paid
    respond_to do |format|
      if @lawsuit.update(lawsuit_params)
        format.html { redirect_to @lawsuit, notice: 'Processo Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @lawsuit }
      else
        format.html { render :edit }
        format.json { render json: @lawsuit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lawsuit
    @lawsuit.destroy
    respond_to do |format|
      format.html { redirect_to lawsuits_path, notice: 'Processo Excluído com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def load_payment
      @payment = Payment.where(lawsuit_id: params[:id]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
    end
    def load_observation
      @observation = Observation.where(lawsuit_id: params[:id]).order("created_at DESC").paginate(page: params[:param_name], per_page: 5)
    end

    def load_annex
      @annex = Annex.where(lawsuit_id: params[:id]).order("created_at DESC").paginate(page: params[:param_name], per_page: 8)
    end
    def load_share
      @share = Share.where(lawsuit_id: params[:id]).order("created_at DESC").paginate(page: params[:param_name], per_page: 8)
    end
    
    def load_client
      @client = Client.find(params[:client_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_lawsuit
      @lawsuit = Lawsuit.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def lawsuit_params
      params.require(:lawsuit).permit(:number, :assessment, :description, :amount, :venue_id, :kind_id, :status_id)
    end
end

app/helpers/annexes_helper.rb
module AnnexesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/lawsuits_helper.rb
module LawsuitsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/lawsuits/_form.html.erb
<div id="novo-processo">
  <h3 id="title">Novo Processo</h3>
  <%= form_for([@client, @client.lawsuits.new]) do |f| %>
    <% if lawsuit.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(lawsuit.errors.count, "error") %> prohibited this lawsuit from being saved:</h2>

        <ul>
        <% lawsuit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="processo-number">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div id="processo-assessment">
      <%= f.label :assessment %>
      <%= f.date_select :assessment %>
    </div>

    <div id="processo-description">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div id="processo-amount">
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </div>

    <div id="processo-venue">
      <%= f.label :venue_id %>
      <%= f.collection_select(:venue_id, Venue.all, :id, :name, {include_blank: true})%>
    </div>

    <div id="processo-kind">
      <%= f.label :kind_id %>
      <%= f.collection_select(:kind_id, Kind.all, :id, :name, {include_blank: true})%>
    </div>

    <div id="processo-status">
      <%= f.label :status_id %>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {include_blank: true})%>
    </div>
    <div id="btn-block">
      <%= f.submit 'Salvar', class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/lawsuits/edit.html.erb
<div id="novo-processo">
  <h3 id="title">Editar Processo</h3>
  <%= form_for(@lawsuit) do |f| %>
    <% if @lawsuit.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@lawsuit.errors.count, "error") %> prohibited this lawsuit from being saved:</h2>
  
        <ul>
        <% @lawsuit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div id="processo-number">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div id="processo-assessment">
      <%= f.label :assessment %>
      <%= f.date_select :assessment %>
    </div>

    <div id="processo-description">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div id="processo-amount">
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </div>

    <div id="processo-venue">
      <%= f.label :venue_id %>
      <%= f.collection_select(:venue_id, Venue.all, :id, :name, {include_blank: true})%>
    </div>

    <div id="processo-kind">
      <%= f.label :kind_id %>
      <%= f.collection_select(:kind_id, Kind.all, :id, :name, {include_blank: true})%>
    </div>

    <div id="processo-status">
      <%= f.label :status_id %>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {include_blank: true})%>
    </div>
    <div id="btn-block">
      <%= f.submit 'Salvar Processo', class: 'btn'%>
    </div>
  <% end %>
</div>

app/views/lawsuits/index.html.erb
<div id="dv-search">
  <strong id="notice"><%= notice %></strong>
  <%= search_form_for @q do |f| %>
    <div id="fields-search"><%= f.search_field :number_cont, placeholder: 'Nº processo' %></div>
    <%= f.submit 'Pesquisar', class: 'btn', :id => 'btn-searchl'%>
  <% end %>
  <%= link_to 'Novo', clients_path, class: 'btn', :id => 'btn-novol' %>
</div>
<div class="main">
  <table>
    <thead>
      <tr>
        <th class="title-tb">Processo</th>
        <th class="title-tb">Cliente</th>
        <th class="title-tb">Status</th>
      </tr>
    </thead>
  
    <tbody>
      <% @lawsuits.each do |lawsuit| %>
        <tr>
          <td class="nro-processo"><%= link_to lawsuit.number, lawsuit %></td>
          <td><%= link_to lawsuit.client.name, lawsuit.client %></td>
          <td><%= lawsuit.status.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="paginate"><%= will_paginate @lawsuits %></div>
</div>

app/views/lawsuits/new.html.erb
<%= render 'form', lawsuit: @lawsuit %>

app/views/lawsuits/show.html.erb
<div class="info-processo">
  <strong id="notice"><%= notice %></strong>
  <strong id="processo">Processo - 
  <%= @lawsuit.number %></strong>
  </br>

  <strong>Data Abertura - </strong>
  <%= "#{l(@lawsuit.assessment)}" %>
  </br>

  <strong>Descrição - </strong>
  <%= @lawsuit.description %>
  </br>

  <strong>Valor Total - </strong>
  <%= "R$ #{@lawsuit.amount}" %>
  </br>

  <strong>Valor pago - </strong>
  <%= "R$ #{@lawsuit.amount_paid}" %>
  </br>
  
  <strong>Valor Restante - </strong>
  <%= "R$ #{@lawsuit.amount_rest}" %>
  </br>
  
  <strong>Advogado - </strong>
  <%= @lawsuit.user.email %>
  </br>

  <strong>Cliente - </strong>
  <%= @lawsuit.client.name %>
  </br>

  <strong>Vara - </strong>
  <%= @lawsuit.venue.name %>
  </br>

  <strong>Natureza - </strong>
  <%= @lawsuit.kind.name %>
  

  <strong>| Status - </strong>
  <%= @lawsuit.status.name %>
  </br>
  <hr>
  <ul class="option">
    <li><%= link_to 'Voltar', lawsuits_path %></li>
    <li><%= link_to 'Editar', edit_lawsuit_path(@lawsuit) %></li>
    <li><%= link_to 'Excluir', @lawsuit, method: :delete, data: { confirm: 'Você tem certeza?' } %></li>
  </ul>
  <hr>
</div>

<div class="share">
  <strong>Compartilhado com</strong>
  <div class="main">
    <table>
      <thead>
        <tr>
          <th class="title-tb">Usuário</th>
        </tr>
      </thead>
  
      <tbody>
        <% @share.each do |share| %>
          <tr>
            <td><%= share.email %></td>
            <td><%= link_to 'Excluir', share, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Compartilhar', new_lawsuit_share_path(lawsuit_id: @lawsuit.id), class: 'btn btn-novo' %>
  </div>
  <div class="paginate"><%= will_paginate @share, param_name: 'share'  %></div>
</div>
<div class="comentario">
  <strong>Comentários</strong>
  <div class="main">
    <table>
      <thead>
        <tr>
          <th class="title-tb">Texto</th>
          <th class="title-tb">Escrito por</th>
        </tr>
      </thead>
  
      <tbody>
        <% @observation.each do |observation| %>
          <tr>
            <td><%= observation.description %></td>
            <td><%= observation.user.email %></td>
            <td><%= link_to 'Editar', edit_observation_path(observation) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Comentar', new_lawsuit_observation_path(lawsuit_id: @lawsuit.id), class:'btn btn-novo' %>
    <div class="paginate"><%= will_paginate @observation, param_name: 'observation'  %></div>
  </div>
</div>

<div class="anexo">
  <strong>Arquivos</strong>
  <div class="main">
    <table>
      <thead>
        <tr>
          <th class="title-tb">Descrição</th>
          <th class="title-tb">Responsável</th>
        </tr>
      </thead>
  
      <tbody>
        <% @annex.each do |annex| %>
          <tr>
            <td><%= link_to annex.description, annex.document.url, :target => "_blank"%></td>
            <td><%= annex.user.email %></td>
            <td><%= link_to 'Editar', edit_annex_path(annex) %></td>
            <td><%= link_to 'Excluir', annex, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Adicionar Arquivo', new_lawsuit_annex_path(lawsuit_id: @lawsuit.id), class: 'btn btn-novo' %>
  </div>
  <div class="paginate"><%= will_paginate @annex, param_name: 'annex'  %></div>
</div>

<div class="pagamento">
  <strong>Pagamentos</strong>
  <div class="main">
    <table>
      <thead>
        <tr>
          <th class="title-tb">Valor Pago</th>
          <th class="title-tb">Data</th>
        </tr>
      </thead>
  
      <tbody>
        <% @payment.each do |payment| %>
          <tr>
            <td><%= payment.amount %></td>
            <td><%= "#{l(payment.created_at)}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Pagamento', new_lawsuit_payment_path(lawsuit_id: @lawsuit.id), class: 'btn btn-novo' %>
  <div class="paginate"><%= will_paginate @payment %></div>
</div>