config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  get 'control_users/index'
  get 'shares/index'
  get 'reports/index'
  get 'welcome/index'
  resources :clients, shallow: true do
    resources :lawsuits
  end
  resources :lawsuits, shallow: true do
    resources :payments
  end
  resources :lawsuits, shallow: true do
    resources :observations
  end
  resources :lawsuits, shallow: true do
    resources :annexes
  end
  resources :lawsuits, shallow: true do
    resources :shares
  end
  resources :addresses

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client
  validates :street, :district, :zipcode, :city, :state, :addresstype, presence: true
end

app/models/annex.rb
class Annex < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
  mount_uploader :document, AnnexUploader
end

app/models/client.rb
class Client < ApplicationRecord
  has_one :address
  belongs_to :user
  has_many :lawsuits
  validates :cpf, :rg, uniqueness: true, presence: true, numericality: { only_integer: true }
  validates :name, :born, :sex, :email, :telephone, :celphone, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
  on: :create }

  accepts_nested_attributes_for :address
end

app/models/kind.rb
class Kind < ApplicationRecord
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/lawsuit.rb
class Lawsuit < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :venue
  belongs_to :kind
  belongs_to :status
  has_many :annexes
  has_many :observations
  has_many :payments
  has_many :shares
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :profiles
	validates :name, uniqueness: true, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :lawsuit
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :lawsuit
end

app/models/status.rb
class Status < ApplicationRecord 
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/user.rb
class User < ApplicationRecord
	enum role: [:normal_user, :admin]
  has_many :clients
  has_many :annexes
  has_one :profile
  has_many :lawsuits
  has_many :observations
  has_many :accounts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
	has_many :lawsuits
	validates :name, presence: true
end

app/controllers/annexes_controller.rb
class AnnexesController < ApplicationController
  before_action :set_annex, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :profile_test
  before_action :load_lawsuit, only: [:new, :create]
  # GET /annexes
  # GET /annexes.json
  def index
    @annexes = Annex.all
  end

  # GET /annexes/1
  # GET /annexes/1.json
  def show
    authorize @annex
  end

  # GET /annexes/new
  def new
    @annex = Annex.new
    @annex.document = params[:file]
  end

  # GET /annexes/1/edit
  def edit
  end

  # POST /annexes
  # POST /annexes.json
  def create
    @annex = @lawsuit.annexes.new(annex_params)
    @annex.user_id = current_user.id
    respond_to do |format|
      if @annex.save
        @annex.document.url
        @annex.document.current_path
        @annex.document_identifier
        format.html { redirect_to @lawsuit, notice: 'Arquivo adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @annex }
      else
        format.html { render :new }
        format.json { render json: @annex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annexes/1
  # PATCH/PUT /annexes/1.json
  def update
    authorize @annex
    respond_to do |format|
      if @annex.update(annex_params)
        format.html { redirect_to lawsuit_path(Lawsuit.find(@annex.lawsuit_id)), notice: 'Arquivo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @annex }
      else
        format.html { render :edit }
        format.json { render json: @annex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annexes/1
  # DELETE /annexes/1.json
  def destroy
    authorize @annex
    id = Lawsuit.find(@annex.lawsuit_id)
    @annex.destroy
    respond_to do |format|
      format.html { redirect_to lawsuit_path(id), notice: 'Arquivo excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annex
      @annex = Annex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annex_params
      params.require(:annex).permit(:description, :document)
    end
end

app/helpers/annexes_helper.rb
module AnnexesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/lawsuits_helper.rb
module LawsuitsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annexes/_form.html.erb
<div class='new-annex'>
  <strong>Novo Arquivo</strong>
  <%= form_for [@lawsuit, @lawsuit.annexes.new], html: { multipart: true } do |f| %>
    <% if annex.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(annex.errors.count, "error") %> prohibited this annex from being saved:</h2>
  
        <ul>
        <% annex.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= f.label :description %>
    <%= f.text_area :description, placeholder:'Digite a descrição aqui....' %>
  
    <%= f.label :document %>
    <%= f.file_field :document %>
    
    <div class='btn-block'>
      <%= f.submit 'Salvar', class:'btn' %>
      <%= link_to 'Voltar', @lawsuit, class:'btn'%>
    </div>
  <% end %>
</div>

app/views/annexes/edit.html.erb
<div class='new-annex'>
  <strong>Editar descrição do arquivo</strong>
  <%= form_for @annex do |f| %>
    <% if @annex.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@annex.errors.count, "error") %> prohibited this annex from being saved:</h2>
  
        <ul>
        <% @annex.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    
    <%= f.label :description %>
    <%= f.text_area :description %>
   
  
    <div class='btn-block'>
      <%= f.submit 'Salvar', class:'btn' %>
      <%= link_to 'Voltar', request.referer, class:'btn'%>
    </div>
  <% end %>
</div>

app/views/annexes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Annexes</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Lawsuit</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annexes.each do |annex| %>
      <tr>
        <td><%= annex.description %></td>
        <td><%= annex.lawsuit %></td>
        <td><%= annex.user %></td>
        <td><%= link_to 'Show', annex %></td>
        <td><%= link_to 'Edit', edit_annex_path(annex) %></td>
        <td><%= link_to 'Destroy', annex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annex', new_annex_path %>

app/views/annexes/new.html.erb
<%= render 'form', annex: @annex %>

app/views/annexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @annex.description %>
</p>

<p>
  <strong>Lawsuit:</strong>
  <%= @annex.lawsuit.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @annex.user.email %>
</p>


<p>
 
  <%= link_to 'Visualizar Arquivo', @annex.document.url %>
</p>

<%= link_to 'Edit', edit_annex_path(@annex) %> |
<%= link_to 'Back', annexes_path %>