config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  get 'control_users/index'
  get 'shares/index'
  get 'reports/index'
  get 'welcome/index'
  resources :clients, shallow: true do
    resources :lawsuits
  end
  resources :lawsuits, shallow: true do
    resources :payments
  end
  resources :lawsuits, shallow: true do
    resources :observations
  end
  resources :lawsuits, shallow: true do
    resources :annexes
  end
  resources :lawsuits, shallow: true do
    resources :shares
  end
  resources :addresses

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :client
  validates :street, :district, :zipcode, :city, :state, :addresstype, presence: true
end

app/models/annex.rb
class Annex < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
  mount_uploader :document, AnnexUploader
end

app/models/client.rb
class Client < ApplicationRecord
  has_one :address
  belongs_to :user
  has_many :lawsuits
  validates :cpf, :rg, uniqueness: true, presence: true, numericality: { only_integer: true }
  validates :name, :born, :sex, :email, :telephone, :celphone, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, 
  on: :create }

  accepts_nested_attributes_for :address
end

app/models/kind.rb
class Kind < ApplicationRecord
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/lawsuit.rb
class Lawsuit < ApplicationRecord
  belongs_to :user
  belongs_to :client
  belongs_to :venue
  belongs_to :kind
  belongs_to :status
  has_many :annexes
  has_many :observations
  has_many :payments
  has_many :shares
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :lawsuit
  belongs_to :user
end

app/models/office.rb
class Office < ApplicationRecord
	has_many :profiles
	validates :name, uniqueness: true, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :lawsuit
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :lawsuit
end

app/models/status.rb
class Status < ApplicationRecord 
	has_many :lawsuits
	validates :name, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
end

app/models/user.rb
class User < ApplicationRecord
	enum role: [:normal_user, :admin]
  has_many :clients
  has_many :annexes
  has_one :profile
  has_many :lawsuits
  has_many :observations
  has_many :accounts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
	has_many :lawsuits
	validates :name, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :profile_test
  before_action :set_lawsuit, only: [:show]

  def index
    @q = Client.ransack(params[:q])
    if params[:q]
      @clients = @q.result
      @clients = policy_scope(@clients).paginate(page: params[:page], per_page: 10)
      if @clients == []
        respond_to do |format|
            format.html { redirect_to clients_url, notice: 'Não foi encontrado.' }
        end
      end
    else
      @clients = policy_scope(Client).paginate(page: params[:page], per_page: 10)

      respond_to do |format|
        format.html
        format.pdf do
          pdf = ClientPdf.new(@clients, "Meus Clientes")
          send_data pdf.render, filename: "lista.pdf", type: "application/pdf", disposition: "inline"
        end
      end
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    authorize @client
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.build_address
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Cliente Cadastrado com Sucesso.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    authorize @client
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Cliente Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    authorize @client
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Cliente Excluído com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_lawsuit
      @lawsuit = Lawsuit.where(client_id: params[:id]).order("status_id ASC").paginate(page: params[:page], per_page: 8)
    end
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :lastname, :born, :sex, :cpf, :rg, :email, :telephone, 
        :celphone, :bio, address_attributes: [:street, :district, :city, :state, :zipcode, :addresstype])
    end
end

app/helpers/annexes_helper.rb
module AnnexesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/lawsuits_helper.rb
module LawsuitsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<div id='novo-cliente'>
  <%= form_for(client) do |f| %>
    <% if client.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

        <ul>
          <% client.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div id="title"><h3>Cadastro de Cliente</h3></div>
    <div id="cliente-name">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div id="cliente-lname">
      <%= f.label :lastname %>
      <%= f.text_field :lastname %>
    </div>
    <div id="cliente-born">
      <%= f.label :born %>
      <%= f.date_select :born, :start_year => 2000, :end_year => 1927, include_blank: true %>
    </div>
    <div id="cliente-sex">
      <%= f.label :sex %>
      <%= f.select(:sex, ['Masculino', 'Feminino'], {include_blank: true})%>
    </div>
    <div id="cliente-cpf">
      <%= f.label :cpf %>
      <%= f.text_field :cpf %>
    </div>
    <div id="cliente-rg">
      <%= f.label :rg %>
      <%= f.text_field :rg %>
    </div>
    <div id="cliente-email">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div id="cliente-telephone">
      <%= f.label :telephone %>
      <%= f.text_field :telephone %>
    </div>
    <div id="cliente-celphone">
      <%= f.label :celphone %>
      <%= f.text_field :celphone %>
    </div>
    <div id="cliente-bio">
      <%= f.label :bio %>
      <%= f.text_area :bio %>
    </div>

    <%= f.fields_for :address do |ff| %>
      <div id="cliente-addresstype">
        <%= ff.label :addresstype %>
        <%= ff.select(:addresstype, ['Residencial', 'Comercial'], {include_blank: true})%>
      </div>
      <div id="cliente-street">
        <%= ff.label :street %>
        <%= ff.text_field :street %>
      </div>
      <div id="cliente-district">
        <%= ff.label :district %>
        <%= ff.text_field :district %>
      </div>
      <div id="cliente-city">
        <%= ff.label :city %>
        <%= ff.text_field :city %>
      </div>
      <div id="cliente-state">
        <%= ff.label :state %>
        <%= ff.select(:state, ['AC','AL', 'AP', 'AM','BA','CE','DF','ES','GO', 'MA','MT','MS', 'MG','PA', 'PB','PR','PE','PI','RJ','RN', 'RS','RO','RR','SC','SP','SE','TO'], {include_blank: true}) %>
      </div>
      <div id="cliente-zipcode">
        <%= ff.label :zipcode %>
        <%= ff.text_field :zipcode %>
      </div>
    <% end %>
    <div id="btn-block">
      <%= link_to 'Voltar', clients_path, class: 'btn', :id => 'btn-voltar' %>
      <%= f.submit 'Salvar', class: 'btn', :id=>'btn-salvar' %>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<div id="dv-search">
  <strong id="notice"><%= notice %></strong>
  <%= search_form_for @q do |f| %>
    <div id="fields-search"><%= f.search_field :cpf_cont, placeholder: 'CPF do Cliente' %></div>
    <%= f.submit 'Pesquisar', class: 'btn', :id => 'btn-search'%>
    <%= link_to 'Novo Cliente', new_client_path, class: 'btn', :id =>'btn-novo' %>
  <% end %>
</div>
<%= link_to  'Imprimir', clients_path(@clients, format: "pdf"), class: "btn bg-flix-secondary text-white", target: "_blank" %>

<div class="main">
  <table class="table">
    <thead class="bg-dark text-light">
      <tr>
        <th class="title-tb">Nome</th>
        <th class="title-tb">CPF</th>
      </tr>
    </thead>
  
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= link_to client.name, client %></td>
          <td><%= client.cpf %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="paginate"><%= will_paginate @clients %></div>
</div>

app/views/clients/new.html.erb
<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<div id="cliente-info">
  <div id="cliente-block-one">
    <div id="title"><h3>Informações do Cliente</h3></div>
    <strong>Cliente - <%= "#{@client.name} " " "" #{@client.lastname}" %></strong></br>
    <strong>Data de Nascimento - </strong><%= "#{l(@client.born)}" %></br>
    <strong>Sexo - </strong><%= @client.sex %></br>  
    <strong>CPF - </strong><%= @client.cpf %></br>  
    <strong>RG - </strong><%= @client.rg %></br>  
    <strong>Observações - </strong> <%= @client.bio %></br>
    <strong>Email - </strong> <%= @client.email %></br>  
    <strong>Telefone - </strong> <%= @client.telephone %></br>
    <strong>Celular - </strong> <%= @client.celphone %></br>
  </div>
  <div id="cliente-block-two">
    <div id="title"><h3>Endereço</h3></div>
    <strong>Tipo de Endereço - </strong> <%= @client.address.addresstype %></br>
    <strong>Rua - </strong> <%= @client.address.street %></br>
    <strong>Bairro - </strong> <%= @client.address.district %></br>  
    <strong>Cidade - </strong> <%= @client.address.city %></br>  
    <strong>Estado - </strong> <%= @client.address.state %></br>   
    <strong>CEP - </strong> <%= @client.address.zipcode %></br>    
  </div>
  <hr>
  <ul id="cliente-action">
    <li><%= link_to 'Voltar', clients_path %></li>
    <li><%= link_to 'Editar', edit_client_path(@client) %></li>
    <li><%= link_to 'Excluir', @client, method: :delete, data: { confirm: 'Você tem certeza?'} %></li>
    <li><%= link_to 'Novo Processo', new_client_lawsuit_path(client_id: @client.id) %></li>
  </ul>
  <hr>
  <div class="comentario">
    <strong>Processos</strong>
    <div class="main">
      <table>
        <thead>
          <tr>
            <th class="title-tb">Número</th>
            <th class="title-tb">Descrição</th>
            <th class="title-tb">Situação</th>
          </tr>
        </thead>
  
        <tbody>
          <% @lawsuit.each do |lawsuit| %>
            <tr>
              <td class="nro-processo"><%= link_to lawsuit.number, lawsuit %></td>
              <td><%= lawsuit.description %></td>
              <td><%= lawsuit.status.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
       <div class="paginate"><%= will_paginate @lawsuit  %></div>
    </div>
  </div>
</div>